#!/bin/bash
# Startup script for a Roboconf agent on Docker
# Find the file containing the messaging configuration
msgConfigFile=$1

# Prepare configuration files
cd /usr/local/roboconf-agent
echo "# Agent configuration - DO NOT EDIT: Generated by Roboconf" > etc/net.roboconf.agent.configuration.cfg
echo "# Messaging configuration - DO NOT EDIT: Generated by Roboconf" > "$msgConfigFile"

# And update them
for p in "$@"
do
	if [[ $p == msg.* ]] ;
		then echo "${p:4}" >> "$msgConfigFile"
	else 
		if [[ $p == agent.* ]] ;
			then echo "${p:6}" >> etc/net.roboconf.agent.configuration.cfg
		fi
	fi
done

# Start Karaf
cd bin
./karaf
